"""empty message

Revision ID: 285d7adde4f3
Revises: d7ed3ac446a8
Create Date: 2023-09-19 19:41:46.529702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285d7adde4f3'
down_revision = 'd7ed3ac446a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
